# API Contracts: dokploy-deployment-platform

# No application API changes for this feature.
# This feature operates at the infrastructure layer (deployment platform).
#
# Dokploy provides its own REST API (internal use only):
# - GET /api/applications - List configured applications
# - POST /api/applications - Create new application
# - GET /api/deployments - List deployment history
# - POST /api/deployments/:id/rollback - Rollback to previous deployment
#
# Dokploy API is authenticated via admin token and not exposed to public.
# Application API contracts remain unchanged.

openapi: 3.0.0
info:
  title: marcusgoll.com API (Unchanged)
  version: 1.0.0
  description: No API changes - infrastructure feature only

paths:
  /api/health:
    get:
      summary: Health check endpoint (existing, unchanged)
      description: Used by Docker health checks and Dokploy monitoring
      responses:
        200:
          description: Application healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
        500:
          description: Application unhealthy
