name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          PUBLIC_URL: "https://marcusgoll.com"
          NEXT_PUBLIC_SITE_URL: "https://marcusgoll.com"
          NODE_ENV: "production"
          # Ghost CMS (using placeholder values for build)
          GHOST_API_URL: "https://demo.ghost.io"
          GHOST_CONTENT_API_KEY: "22444f78447824223cefc48062" # Demo key
          # Optional vars (not required for build)
          DATABASE_URL: ""
          NEXTAUTH_SECRET: ""
          NEXTAUTH_URL: ""
          RESEND_API_KEY: ""
          ADMIN_EMAIL: ""
        run: npm run build

      - name: Lint check
        run: npm run lint
        continue-on-error: true

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [build]
    if: always()

    steps:
      - name: Check build status
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
            echo "Build failed. Check logs above."
            exit 1
          fi
          echo "All checks passed!"
